CREATE TABLE IF NOT EXISTS ip_requests (
  ip_hash TEXT PRIMARY KEY,
  count INTEGER DEFAULT 0,
  last_request_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
